### ISSUE TITLE
afternoon data are missing for hourly data

### ISSUE THREAD

**Issue by fanqi203** [aazuspan/eexarray#2]
When I use convert an hourly EE image collection to xarray, the afternoon hours are all missing. 

![image](https://user-images.githubusercontent.com/13813022/128264670-747eda92-d0ca-4d33-8ba4-3d9566792c8b.png)

![image](https://user-images.githubusercontent.com/13813022/128264778-4f1d4063-962d-4509-bf19-175a8de517a4.png)

**Comment by aazuspan** [comment]
Thanks for letting me know @fanqi203! I just pushed a fix that should resolve this bug.

**Comment by fanqi203** [comment]
Thanks!
